/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppCompetitionRouteImport } from './routes/app/competition/route'
import { Route as AppSearchUsersIndexImport } from './routes/app/search-users/index'
import { Route as AppProfileIndexImport } from './routes/app/profile/index'
import { Route as AppPracticeIndexImport } from './routes/app/practice/index'
import { Route as AppOnlineIndexImport } from './routes/app/online/index'
import { Route as AppFriendRequestsIndexImport } from './routes/app/friend-requests/index'
import { Route as AppCompetitionIndexImport } from './routes/app/competition/index'
import { Route as AppProfileEditIndexImport } from './routes/app/profile/edit/index'
import { Route as AppPracticeRapidIndexImport } from './routes/app/practice/rapid/index'
import { Route as AppPracticeFlowIndexImport } from './routes/app/practice/flow/index'
import { Route as AppChatFriendIdIndexImport } from './routes/app/chat/$friendId/index'
import { Route as AppCompetitionResultIdImport } from './routes/app/competition/result/$id'
import { Route as AppOnlineRoomIdRouteImport } from './routes/app/online/room/$id/route'
import { Route as AppOnlineRoomIdIndexImport } from './routes/app/online/room/$id/index'
import { Route as AppCompetitionPlayRapidIndexImport } from './routes/app/competition/play/rapid/index'
import { Route as AppCompetitionPlayFlowIndexImport } from './routes/app/competition/play/flow/index'
import { Route as AppOnlineRoomIdMembersIndexImport } from './routes/app/online/room/$id/members/index'
import { Route as AppOnlineRoomIdLeaderboardIndexImport } from './routes/app/online/room/$id/leaderboard/index'
import { Route as AppOnlineRoomIdChatIndexImport } from './routes/app/online/room/$id/chat/index'

// Create/Update Routes

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AppCompetitionRouteRoute = AppCompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSearchUsersIndexRoute = AppSearchUsersIndexImport.update({
  id: '/search-users/',
  path: '/search-users/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppPracticeIndexRoute = AppPracticeIndexImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppOnlineIndexRoute = AppOnlineIndexImport.update({
  id: '/online/',
  path: '/online/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppFriendRequestsIndexRoute = AppFriendRequestsIndexImport.update({
  id: '/friend-requests/',
  path: '/friend-requests/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCompetitionIndexRoute = AppCompetitionIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompetitionRouteRoute,
} as any)

const AppProfileEditIndexRoute = AppProfileEditIndexImport.update({
  id: '/profile/edit/',
  path: '/profile/edit/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppPracticeRapidIndexRoute = AppPracticeRapidIndexImport.update({
  id: '/practice/rapid/',
  path: '/practice/rapid/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppPracticeFlowIndexRoute = AppPracticeFlowIndexImport.update({
  id: '/practice/flow/',
  path: '/practice/flow/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppChatFriendIdIndexRoute = AppChatFriendIdIndexImport.update({
  id: '/chat/$friendId/',
  path: '/chat/$friendId/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCompetitionResultIdRoute = AppCompetitionResultIdImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => AppCompetitionRouteRoute,
} as any)

const AppOnlineRoomIdRouteRoute = AppOnlineRoomIdRouteImport.update({
  id: '/online/room/$id',
  path: '/online/room/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppOnlineRoomIdIndexRoute = AppOnlineRoomIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOnlineRoomIdRouteRoute,
} as any)

const AppCompetitionPlayRapidIndexRoute =
  AppCompetitionPlayRapidIndexImport.update({
    id: '/play/rapid/',
    path: '/play/rapid/',
    getParentRoute: () => AppCompetitionRouteRoute,
  } as any)

const AppCompetitionPlayFlowIndexRoute =
  AppCompetitionPlayFlowIndexImport.update({
    id: '/play/flow/',
    path: '/play/flow/',
    getParentRoute: () => AppCompetitionRouteRoute,
  } as any)

const AppOnlineRoomIdMembersIndexRoute =
  AppOnlineRoomIdMembersIndexImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AppOnlineRoomIdRouteRoute,
  } as any)

const AppOnlineRoomIdLeaderboardIndexRoute =
  AppOnlineRoomIdLeaderboardIndexImport.update({
    id: '/leaderboard/',
    path: '/leaderboard/',
    getParentRoute: () => AppOnlineRoomIdRouteRoute,
  } as any)

const AppOnlineRoomIdChatIndexRoute = AppOnlineRoomIdChatIndexImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppOnlineRoomIdRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/app/competition': {
      id: '/app/competition'
      path: '/competition'
      fullPath: '/app/competition'
      preLoaderRoute: typeof AppCompetitionRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof AuthRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/competition/': {
      id: '/app/competition/'
      path: '/'
      fullPath: '/app/competition/'
      preLoaderRoute: typeof AppCompetitionIndexImport
      parentRoute: typeof AppCompetitionRouteImport
    }
    '/app/friend-requests/': {
      id: '/app/friend-requests/'
      path: '/friend-requests'
      fullPath: '/app/friend-requests'
      preLoaderRoute: typeof AppFriendRequestsIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/online/': {
      id: '/app/online/'
      path: '/online'
      fullPath: '/app/online'
      preLoaderRoute: typeof AppOnlineIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/practice/': {
      id: '/app/practice/'
      path: '/practice'
      fullPath: '/app/practice'
      preLoaderRoute: typeof AppPracticeIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/search-users/': {
      id: '/app/search-users/'
      path: '/search-users'
      fullPath: '/app/search-users'
      preLoaderRoute: typeof AppSearchUsersIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/online/room/$id': {
      id: '/app/online/room/$id'
      path: '/online/room/$id'
      fullPath: '/app/online/room/$id'
      preLoaderRoute: typeof AppOnlineRoomIdRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/competition/result/$id': {
      id: '/app/competition/result/$id'
      path: '/result/$id'
      fullPath: '/app/competition/result/$id'
      preLoaderRoute: typeof AppCompetitionResultIdImport
      parentRoute: typeof AppCompetitionRouteImport
    }
    '/app/chat/$friendId/': {
      id: '/app/chat/$friendId/'
      path: '/chat/$friendId'
      fullPath: '/app/chat/$friendId'
      preLoaderRoute: typeof AppChatFriendIdIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/practice/flow/': {
      id: '/app/practice/flow/'
      path: '/practice/flow'
      fullPath: '/app/practice/flow'
      preLoaderRoute: typeof AppPracticeFlowIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/practice/rapid/': {
      id: '/app/practice/rapid/'
      path: '/practice/rapid'
      fullPath: '/app/practice/rapid'
      preLoaderRoute: typeof AppPracticeRapidIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/profile/edit/': {
      id: '/app/profile/edit/'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/app/competition/play/flow/': {
      id: '/app/competition/play/flow/'
      path: '/play/flow'
      fullPath: '/app/competition/play/flow'
      preLoaderRoute: typeof AppCompetitionPlayFlowIndexImport
      parentRoute: typeof AppCompetitionRouteImport
    }
    '/app/competition/play/rapid/': {
      id: '/app/competition/play/rapid/'
      path: '/play/rapid'
      fullPath: '/app/competition/play/rapid'
      preLoaderRoute: typeof AppCompetitionPlayRapidIndexImport
      parentRoute: typeof AppCompetitionRouteImport
    }
    '/app/online/room/$id/': {
      id: '/app/online/room/$id/'
      path: '/'
      fullPath: '/app/online/room/$id/'
      preLoaderRoute: typeof AppOnlineRoomIdIndexImport
      parentRoute: typeof AppOnlineRoomIdRouteImport
    }
    '/app/online/room/$id/chat/': {
      id: '/app/online/room/$id/chat/'
      path: '/chat'
      fullPath: '/app/online/room/$id/chat'
      preLoaderRoute: typeof AppOnlineRoomIdChatIndexImport
      parentRoute: typeof AppOnlineRoomIdRouteImport
    }
    '/app/online/room/$id/leaderboard/': {
      id: '/app/online/room/$id/leaderboard/'
      path: '/leaderboard'
      fullPath: '/app/online/room/$id/leaderboard'
      preLoaderRoute: typeof AppOnlineRoomIdLeaderboardIndexImport
      parentRoute: typeof AppOnlineRoomIdRouteImport
    }
    '/app/online/room/$id/members/': {
      id: '/app/online/room/$id/members/'
      path: '/members'
      fullPath: '/app/online/room/$id/members'
      preLoaderRoute: typeof AppOnlineRoomIdMembersIndexImport
      parentRoute: typeof AppOnlineRoomIdRouteImport
    }
  }
}

// Create and export the route tree

interface AppCompetitionRouteRouteChildren {
  AppCompetitionIndexRoute: typeof AppCompetitionIndexRoute
  AppCompetitionResultIdRoute: typeof AppCompetitionResultIdRoute
  AppCompetitionPlayFlowIndexRoute: typeof AppCompetitionPlayFlowIndexRoute
  AppCompetitionPlayRapidIndexRoute: typeof AppCompetitionPlayRapidIndexRoute
}

const AppCompetitionRouteRouteChildren: AppCompetitionRouteRouteChildren = {
  AppCompetitionIndexRoute: AppCompetitionIndexRoute,
  AppCompetitionResultIdRoute: AppCompetitionResultIdRoute,
  AppCompetitionPlayFlowIndexRoute: AppCompetitionPlayFlowIndexRoute,
  AppCompetitionPlayRapidIndexRoute: AppCompetitionPlayRapidIndexRoute,
}

const AppCompetitionRouteRouteWithChildren =
  AppCompetitionRouteRoute._addFileChildren(AppCompetitionRouteRouteChildren)

interface AppOnlineRoomIdRouteRouteChildren {
  AppOnlineRoomIdIndexRoute: typeof AppOnlineRoomIdIndexRoute
  AppOnlineRoomIdChatIndexRoute: typeof AppOnlineRoomIdChatIndexRoute
  AppOnlineRoomIdLeaderboardIndexRoute: typeof AppOnlineRoomIdLeaderboardIndexRoute
  AppOnlineRoomIdMembersIndexRoute: typeof AppOnlineRoomIdMembersIndexRoute
}

const AppOnlineRoomIdRouteRouteChildren: AppOnlineRoomIdRouteRouteChildren = {
  AppOnlineRoomIdIndexRoute: AppOnlineRoomIdIndexRoute,
  AppOnlineRoomIdChatIndexRoute: AppOnlineRoomIdChatIndexRoute,
  AppOnlineRoomIdLeaderboardIndexRoute: AppOnlineRoomIdLeaderboardIndexRoute,
  AppOnlineRoomIdMembersIndexRoute: AppOnlineRoomIdMembersIndexRoute,
}

const AppOnlineRoomIdRouteRouteWithChildren =
  AppOnlineRoomIdRouteRoute._addFileChildren(AppOnlineRoomIdRouteRouteChildren)

interface AppRouteRouteChildren {
  AppCompetitionRouteRoute: typeof AppCompetitionRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppFriendRequestsIndexRoute: typeof AppFriendRequestsIndexRoute
  AppOnlineIndexRoute: typeof AppOnlineIndexRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSearchUsersIndexRoute: typeof AppSearchUsersIndexRoute
  AppOnlineRoomIdRouteRoute: typeof AppOnlineRoomIdRouteRouteWithChildren
  AppChatFriendIdIndexRoute: typeof AppChatFriendIdIndexRoute
  AppPracticeFlowIndexRoute: typeof AppPracticeFlowIndexRoute
  AppPracticeRapidIndexRoute: typeof AppPracticeRapidIndexRoute
  AppProfileEditIndexRoute: typeof AppProfileEditIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCompetitionRouteRoute: AppCompetitionRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppFriendRequestsIndexRoute: AppFriendRequestsIndexRoute,
  AppOnlineIndexRoute: AppOnlineIndexRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSearchUsersIndexRoute: AppSearchUsersIndexRoute,
  AppOnlineRoomIdRouteRoute: AppOnlineRoomIdRouteRouteWithChildren,
  AppChatFriendIdIndexRoute: AppChatFriendIdIndexRoute,
  AppPracticeFlowIndexRoute: AppPracticeFlowIndexRoute,
  AppPracticeRapidIndexRoute: AppPracticeRapidIndexRoute,
  AppProfileEditIndexRoute: AppProfileEditIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/competition': typeof AppCompetitionRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/competition/': typeof AppCompetitionIndexRoute
  '/app/friend-requests': typeof AppFriendRequestsIndexRoute
  '/app/online': typeof AppOnlineIndexRoute
  '/app/practice': typeof AppPracticeIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/search-users': typeof AppSearchUsersIndexRoute
  '/app/online/room/$id': typeof AppOnlineRoomIdRouteRouteWithChildren
  '/app/competition/result/$id': typeof AppCompetitionResultIdRoute
  '/app/chat/$friendId': typeof AppChatFriendIdIndexRoute
  '/app/practice/flow': typeof AppPracticeFlowIndexRoute
  '/app/practice/rapid': typeof AppPracticeRapidIndexRoute
  '/app/profile/edit': typeof AppProfileEditIndexRoute
  '/app/competition/play/flow': typeof AppCompetitionPlayFlowIndexRoute
  '/app/competition/play/rapid': typeof AppCompetitionPlayRapidIndexRoute
  '/app/online/room/$id/': typeof AppOnlineRoomIdIndexRoute
  '/app/online/room/$id/chat': typeof AppOnlineRoomIdChatIndexRoute
  '/app/online/room/$id/leaderboard': typeof AppOnlineRoomIdLeaderboardIndexRoute
  '/app/online/room/$id/members': typeof AppOnlineRoomIdMembersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/app/competition': typeof AppCompetitionIndexRoute
  '/app/friend-requests': typeof AppFriendRequestsIndexRoute
  '/app/online': typeof AppOnlineIndexRoute
  '/app/practice': typeof AppPracticeIndexRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/search-users': typeof AppSearchUsersIndexRoute
  '/app/competition/result/$id': typeof AppCompetitionResultIdRoute
  '/app/chat/$friendId': typeof AppChatFriendIdIndexRoute
  '/app/practice/flow': typeof AppPracticeFlowIndexRoute
  '/app/practice/rapid': typeof AppPracticeRapidIndexRoute
  '/app/profile/edit': typeof AppProfileEditIndexRoute
  '/app/competition/play/flow': typeof AppCompetitionPlayFlowIndexRoute
  '/app/competition/play/rapid': typeof AppCompetitionPlayRapidIndexRoute
  '/app/online/room/$id': typeof AppOnlineRoomIdIndexRoute
  '/app/online/room/$id/chat': typeof AppOnlineRoomIdChatIndexRoute
  '/app/online/room/$id/leaderboard': typeof AppOnlineRoomIdLeaderboardIndexRoute
  '/app/online/room/$id/members': typeof AppOnlineRoomIdMembersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/competition': typeof AppCompetitionRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/app/competition/': typeof AppCompetitionIndexRoute
  '/app/friend-requests/': typeof AppFriendRequestsIndexRoute
  '/app/online/': typeof AppOnlineIndexRoute
  '/app/practice/': typeof AppPracticeIndexRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/search-users/': typeof AppSearchUsersIndexRoute
  '/app/online/room/$id': typeof AppOnlineRoomIdRouteRouteWithChildren
  '/app/competition/result/$id': typeof AppCompetitionResultIdRoute
  '/app/chat/$friendId/': typeof AppChatFriendIdIndexRoute
  '/app/practice/flow/': typeof AppPracticeFlowIndexRoute
  '/app/practice/rapid/': typeof AppPracticeRapidIndexRoute
  '/app/profile/edit/': typeof AppProfileEditIndexRoute
  '/app/competition/play/flow/': typeof AppCompetitionPlayFlowIndexRoute
  '/app/competition/play/rapid/': typeof AppCompetitionPlayRapidIndexRoute
  '/app/online/room/$id/': typeof AppOnlineRoomIdIndexRoute
  '/app/online/room/$id/chat/': typeof AppOnlineRoomIdChatIndexRoute
  '/app/online/room/$id/leaderboard/': typeof AppOnlineRoomIdLeaderboardIndexRoute
  '/app/online/room/$id/members/': typeof AppOnlineRoomIdMembersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/competition'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/competition/'
    | '/app/friend-requests'
    | '/app/online'
    | '/app/practice'
    | '/app/profile'
    | '/app/search-users'
    | '/app/online/room/$id'
    | '/app/competition/result/$id'
    | '/app/chat/$friendId'
    | '/app/practice/flow'
    | '/app/practice/rapid'
    | '/app/profile/edit'
    | '/app/competition/play/flow'
    | '/app/competition/play/rapid'
    | '/app/online/room/$id/'
    | '/app/online/room/$id/chat'
    | '/app/online/room/$id/leaderboard'
    | '/app/online/room/$id/members'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/login'
    | '/auth/signup'
    | '/app'
    | '/app/competition'
    | '/app/friend-requests'
    | '/app/online'
    | '/app/practice'
    | '/app/profile'
    | '/app/search-users'
    | '/app/competition/result/$id'
    | '/app/chat/$friendId'
    | '/app/practice/flow'
    | '/app/practice/rapid'
    | '/app/profile/edit'
    | '/app/competition/play/flow'
    | '/app/competition/play/rapid'
    | '/app/online/room/$id'
    | '/app/online/room/$id/chat'
    | '/app/online/room/$id/leaderboard'
    | '/app/online/room/$id/members'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/competition'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/app/competition/'
    | '/app/friend-requests/'
    | '/app/online/'
    | '/app/practice/'
    | '/app/profile/'
    | '/app/search-users/'
    | '/app/online/room/$id'
    | '/app/competition/result/$id'
    | '/app/chat/$friendId/'
    | '/app/practice/flow/'
    | '/app/practice/rapid/'
    | '/app/profile/edit/'
    | '/app/competition/play/flow/'
    | '/app/competition/play/rapid/'
    | '/app/online/room/$id/'
    | '/app/online/room/$id/chat/'
    | '/app/online/room/$id/leaderboard/'
    | '/app/online/room/$id/members/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/competition",
        "/app/",
        "/app/friend-requests/",
        "/app/online/",
        "/app/practice/",
        "/app/profile/",
        "/app/search-users/",
        "/app/online/room/$id",
        "/app/chat/$friendId/",
        "/app/practice/flow/",
        "/app/practice/rapid/",
        "/app/profile/edit/"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/login",
        "/auth/signup"
      ]
    },
    "/app/competition": {
      "filePath": "app/competition/route.tsx",
      "parent": "/app",
      "children": [
        "/app/competition/",
        "/app/competition/result/$id",
        "/app/competition/play/flow/",
        "/app/competition/play/rapid/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx",
      "parent": "/auth"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx",
      "parent": "/auth"
    },
    "/app/": {
      "filePath": "app/index.tsx",
      "parent": "/app"
    },
    "/app/competition/": {
      "filePath": "app/competition/index.tsx",
      "parent": "/app/competition"
    },
    "/app/friend-requests/": {
      "filePath": "app/friend-requests/index.tsx",
      "parent": "/app"
    },
    "/app/online/": {
      "filePath": "app/online/index.tsx",
      "parent": "/app"
    },
    "/app/practice/": {
      "filePath": "app/practice/index.tsx",
      "parent": "/app"
    },
    "/app/profile/": {
      "filePath": "app/profile/index.tsx",
      "parent": "/app"
    },
    "/app/search-users/": {
      "filePath": "app/search-users/index.tsx",
      "parent": "/app"
    },
    "/app/online/room/$id": {
      "filePath": "app/online/room/$id/route.tsx",
      "parent": "/app",
      "children": [
        "/app/online/room/$id/",
        "/app/online/room/$id/chat/",
        "/app/online/room/$id/leaderboard/",
        "/app/online/room/$id/members/"
      ]
    },
    "/app/competition/result/$id": {
      "filePath": "app/competition/result/$id.tsx",
      "parent": "/app/competition"
    },
    "/app/chat/$friendId/": {
      "filePath": "app/chat/$friendId/index.tsx",
      "parent": "/app"
    },
    "/app/practice/flow/": {
      "filePath": "app/practice/flow/index.tsx",
      "parent": "/app"
    },
    "/app/practice/rapid/": {
      "filePath": "app/practice/rapid/index.tsx",
      "parent": "/app"
    },
    "/app/profile/edit/": {
      "filePath": "app/profile/edit/index.tsx",
      "parent": "/app"
    },
    "/app/competition/play/flow/": {
      "filePath": "app/competition/play/flow/index.tsx",
      "parent": "/app/competition"
    },
    "/app/competition/play/rapid/": {
      "filePath": "app/competition/play/rapid/index.tsx",
      "parent": "/app/competition"
    },
    "/app/online/room/$id/": {
      "filePath": "app/online/room/$id/index.tsx",
      "parent": "/app/online/room/$id"
    },
    "/app/online/room/$id/chat/": {
      "filePath": "app/online/room/$id/chat/index.tsx",
      "parent": "/app/online/room/$id"
    },
    "/app/online/room/$id/leaderboard/": {
      "filePath": "app/online/room/$id/leaderboard/index.tsx",
      "parent": "/app/online/room/$id"
    },
    "/app/online/room/$id/members/": {
      "filePath": "app/online/room/$id/members/index.tsx",
      "parent": "/app/online/room/$id"
    }
  }
}
ROUTE_MANIFEST_END */
